package es.iespuertodelacruz.alejandrosamuel.studycircle.infrastructure.enums;

public enum RespuestasCurso {
    COURSE_DTO_NOT_VALID,
    STUDENT_PROFILE_NOT_CREATED,
    TUTOR_PROFILE_NOT_CREATED,
    INVALID_PARAMETERS,
    NON_EXISTING_COURSE_OR_STUDENT,
    NON_EXISTING_COURSE,
    NON_AUTHENTICATED_OWNER,
    NON_AUTHORIZED_SUBJECT,
    COURSE_REMOVED,
    COURSE_NOT_REMOVED,
    STUDENT_INVITED,
    STUDENT_OR_COURSE_NOT_FOUND,
    STUDENT_NOT_FOUND_IN_CONTACTS,
    ALERT_NOT_FOUND,
    STUDENT_OR_INVITATION_NOT_FOUND,
    INVITATION_REMOVED,
    USER_ALREADY_IN_COURSE_OR_INVITED
}
